import type { NextPage } from 'next';
import Head from 'next/head';

import About from '../components/About/About';
import Hero from '../components/Hero/Hero';
import ResponsiveNavBar from '../components/ResponsiveNavBar/ResponsiveNavBar';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveNavBar />
      <Hero />
      <About />
    </div>
  );
};

export default Home;
